# Book settings
title: Lab in C&P (Fall 2026)
author: Todd M. Gureckis
logo: images/logo/artificialintelligence.svg

html:
  favicon: "images/favicon.ico"
  home_page_in_navbar: false

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - html_image

bibtex_bibfiles:
    - references.bib
    
repository:
  url: https://github.com/maya-malaviya/nyu_lab_in_cognition
  path_to_book: book/
  branch: main


launch_buttons:
  notebook_interface: "classic"
  jupyterhub_url: "https://psych-ua46-spring.rcnyu.org/"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)
  binderhub_url: ""
